language: node_js
sudo: false
install: yarn

env:
  matrix:
    - CXX=g++-4.8 TEST_ISTRAVIS=true DB_TYPE=mysql2 DB_HOST=127.0.0.1 DB_PORT=3306 DB_NAME=ess DB_USER=root DB_PASS=

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - mysql

node_js:
  - "stable"

before_install:
  - mysql -e 'create database ess;'

before_script:
  - yarn run gulp:build
  - yarn run db:migrate
